apiVersion: autoscaling.k8s.io/v1
ekn:
  gitOpsTarget: everything
kind: VerticalPodAutoscaler
metadata:
  name: caph-controller-manager
  namespace: caph-system
spec:
  targetRef:
    apiVersion: v1
    kind: Deployment
    name: caph-controller-manager
  updatePolicy:
    updateMode: InPlaceOrRecreate
