apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-system/vertical-pod-autoscaler-admission-controller
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/component-instance: vertical-pod-autoscaler-admission-controller
    app.kubernetes.io/instance: vertical-pod-autoscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/version: 1.7.1
    helm.sh/chart: vertical-pod-autoscaler-1.12.1
  name: vpa-webhook-config
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vertical-pod-autoscaler-admission-controller
      namespace: kube-system
  failurePolicy: Ignore
  name: vpa.k8s.io
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  - apiGroups:
    - autoscaling.k8s.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - verticalpodautoscalers
  sideEffects: None
