apiVersion: source.toolkit.fluxcd.io/v1
ekn:
  gitOpsTarget: everything
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1h
  url: https://kyverno.github.io/kyverno
