apiVersion: external-secrets.io/v1
ekn:
  gitOpsTarget: everything
kind: ExternalSecret
metadata:
  name: admin
  namespace: pgadmin
spec:
  data:
  - remoteRef:
      key: name:pgadmin-admin
      property: username
    secretKey: username
  - remoteRef:
      key: name:pgadmin-admin
      property: password
    secretKey: password
  refreshInterval: 30m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway
  target:
    template:
      type: kubernetes.io/basic-auth
