apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/ttl: '60'
  name: keycloak
  namespace: keycloak
spec:
  hostnames:
  - keycloak.lillecarl.com
  parentRefs:
  - name: default
    namespace: kube-system
  rules:
  - backendRefs:
    - name: keycloak
      port: 8080
    matches:
    - path:
        type: PathPrefix
        value: /
