apiVersion: v1
automountServiceAccountToken: true
ekn:
  gitOpsTarget: everything
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: hcloud-csi
    app.kubernetes.io/name: hcloud-csi
  name: hcloud-csi-controller
  namespace: kube-system
