apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: metrics
  namespace: observability
spec:
  datasource:
    url: http://vmsingle-metrics:8429
  evaluationInterval: 30s
  extraArgs:
    external.url: https://vmalert-metrics.lillecarl.com
  notifiers:
  - url: http://vmalertmanager-alertmanager.observability.svc:9093
  remoteWrite:
    url: http://vmsingle-metrics:8429
  ruleSelector:
    matchLabels:
      role: metrics
