apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ep-ingress-label
spec:
  endpointSelector:
    matchLabels:
      cilium.io/ingress: 'true'
  ingress:
  - fromEntities:
    - all
