apiVersion: v1
ekn:
  gitOpsTarget: everything
kind: Secret
metadata:
  name: scaleway
  namespace: kube-system
stringData:
  SCW_ACCESS_KEY: '{{ SCW_ACCESS_KEY }}'
  SCW_SECRET_KEY: '{{ SCW_SECRET_KEY }}'
