apiVersion: storage.k8s.io/v1
ekn:
  gitOpsTarget: everything
kind: CSIDriver
metadata:
  name: csi.hetzner.cloud
spec:
  attachRequired: true
  fsGroupPolicy: File
  podInfoOnMount: true
  seLinuxMount: true
  volumeLifecycleModes:
  - Persistent
