apiVersion: v1
ekn:
  gitOpsTarget: everything
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: victoria-metrics-operator
  name: vm
