apiVersion: v1
ekn:
  gitOpsTarget: everything
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.19.0
  name: kube-state-metrics
  namespace: observability
spec:
  clusterIP: None
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
