apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram
  namespace: observability
spec:
  data:
  - remoteRef:
      key: telegram-bot-token
    secretKey: token
  refreshInterval: 30m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    template:
      type: Opaque
