apiVersion: autoscaling.k8s.io/v1
ekn:
  gitOpsTarget: everything
kind: VerticalPodAutoscaler
metadata:
  name: external-dns-cloudflare
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-dns-cloudflare
  updatePolicy:
    updateMode: InPlaceOrRecreate
