apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
  namespace: observability
spec:
  datasource:
    access: proxy
    isDefault: true
    jsonData:
      handleGrafanaManagedAlerts: false
      implementation: prometheus
    name: Alertmanager
    type: alertmanager
    url: http://vmalertmanager-alertmanager.observability.svc.cluster.local:9093
  instanceSelector:
    matchLabels:
      dashboards: grafana
