apiVersion: grafana.integreatly.org/v1beta1
ekn:
  gitOpsTarget: everything
kind: GrafanaDatasource
metadata:
  name: vlsingle
  namespace: observability
spec:
  datasource:
    access: proxy
    name: VictoriaLogs
    type: victoriametrics-logs-datasource
    url: http://vlsingle-logs.observability.svc.cluster.local:9428
  instanceSelector:
    matchLabels:
      dashboards: grafana
