apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
ekn:
  gitOpsTarget: everything
kind: HCloudMachineTemplate
metadata:
  name: hetzkube-workers-arm64
  namespace: hetzkube
spec:
  template:
    spec:
      imageName: 2505-arm
      placementGroupName: workers
      type: cax11
