apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium
  namespace: kube-system
spec:
  service:
    ipFamilies:
    - IPv4
    - IPv6
    ipFamilyPolicy: RequireDualStack
