apiVersion: generators.external-secrets.io/v1alpha1
ekn:
  gitOpsTarget: everything
kind: ClusterGenerator
metadata:
  name: crappy-pw
spec:
  generator:
    passwordSpec:
      length: 16
      symbols: 0
  kind: Password
