apiVersion: v1
ekn:
  gitOpsTarget: everything
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: keycloak
  name: keycloak-discovery
  namespace: keycloak
spec:
  clusterIP: None
  ipFamilyPolicy: RequireDualStack
  selector:
    app.kubernetes.io/name: keycloak
  type: ClusterIP
