apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-primaryswap
  namespace: database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cnpg-primaryswap
subjects:
- kind: ServiceAccount
  name: cnpg-primaryswap
  namespace: database
