apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
    k8s-app: coredns
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: CoreDNS
    prometheus.io/port: '9153'
    prometheus.io/scrape: 'true'
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.134.0.10
  clusterIPs:
  - 10.134.0.10
  - fdce:9c4d:dcba::10
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: udp-53
    port: 53
    protocol: UDP
    targetPort: 53
  - name: tcp-53
    port: 53
    protocol: TCP
    targetPort: 53
  - name: http-metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: coredns
  type: ClusterIP
