apiVersion: v1
ekn:
  gitOpsTarget: everything
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/version: v2.6.0
    external-secrets.io/component: webhook
    helm.sh/chart: external-secrets-2.6.0
  name: external-secrets-webhook
  namespace: kube-system
spec:
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/name: external-secrets-webhook
  type: ClusterIP
