apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: hcloud-csi
    app.kubernetes.io/name: hcloud-csi
  name: hcloud-csi-controller-metrics
  namespace: kube-system
spec:
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: metrics
    port: 9189
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: hcloud-csi
    app.kubernetes.io/name: hcloud-csi
