apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/component-instance: vertical-pod-autoscaler-admission-controller
    app.kubernetes.io/instance: vertical-pod-autoscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/version: 1.7.1
    helm.sh/chart: vertical-pod-autoscaler-1.12.1
  name: vertical-pod-autoscaler-admission-controller
  namespace: kube-system
spec:
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: http-metrics
    port: 8944
    targetPort: http-metrics
  - name: https
    port: 443
    targetPort: http
  selector:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: vertical-pod-autoscaler
    app.kubernetes.io/name: vertical-pod-autoscaler
  type: ClusterIP
