apiVersion: v1
data:
  clientID: aGVhZGxhbXA=
  issuerURL: aHR0cHM6Ly9rZXljbG9hay5saWxsZWNhcmwuY29tL3JlYWxtcy9hdXRo
  scopes: b3BlbmlkLGVtYWlsLHByb2ZpbGUsb2ZmbGluZV9hY2Nlc3M=
  usePKCE: dHJ1ZQ==
ekn:
  gitOpsTarget: everything
kind: Secret
metadata:
  name: oidc
  namespace: headlamp
type: Opaque
