apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    nodepool: hetzkube-workers-arm64
  name: hetzkube-workers-arm64
  namespace: hetzkube
spec:
  clusterName: hetzkube
  replicas: 0
  selector: {}
  template:
    metadata:
      labels:
        nodepool: hetzkube-workers-arm64
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: hetzkube-workers
      clusterName: hetzkube
      failureDomain: hel1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: hetzkube-workers-arm64
      version: v1.36.2
