apiVersion: autoscaling.k8s.io/v1
ekn:
  gitOpsTarget: everything
kind: VerticalPodAutoscaler
metadata:
  name: keycloak
  namespace: keycloak
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: keycloak
  updatePolicy:
    updateMode: InPlaceOrRecreate
