apiVersion: v1
ekn:
  gitOpsTarget: everything
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vm-operator
  name: vm-operator
  namespace: vm
