apiVersion: autoscaling.k8s.io/v1
ekn:
  gitOpsTarget: everything
kind: VerticalPodAutoscaler
metadata:
  name: capi-controller-manager
  namespace: capi-system
spec:
  targetRef:
    apiVersion: v1
    kind: Deployment
    name: capi-controller-manager
  updatePolicy:
    updateMode: InPlaceOrRecreate
