apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: kube-system
spec:
  data:
  - remoteRef:
      key: cloudflare-token
    secretKey: token
  refreshInterval: 30m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    template:
      type: Opaque
