apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-verify-keycloak-grafana
  namespace: kube-system
spec:
  data:
  - remoteRef:
      key: keycloak-grafana
    secretKey: client-secret
  refreshInterval: 30m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    template:
      type: Opaque
