apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scaleway-dns-key
  namespace: kube-system
spec:
  data:
  - remoteRef:
      key: name:scaleway-dns-key
      property: username
    secretKey: username
  - remoteRef:
      key: name:scaleway-dns-key
      property: password
    secretKey: password
  refreshInterval: 30m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway
  target:
    template:
      type: kubernetes.io/basic-auth
