apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  chart:
    spec:
      chart: vertical-pod-autoscaler
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
        namespace: kube-system
      version: '*'
  driftDetection:
    ignore: []
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 1h
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    admissionController:
      certManager:
        enabled: true
    recommender:
      extraArgs:
      - --pod-recommendation-min-memory-mb=20
      - --pod-recommendation-min-cpu-millicores=25
    updater:
      extraArgs:
      - --min-replicas=1
      - --eviction-tolerance=1.0
      - --in-recommendation-bounds-eviction-lifetime-threshold=3h
