apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pgadmin
  updatePolicy:
    updateMode: InPlaceOrRecreate
