apiVersion: autoscaling.k8s.io/v1
ekn:
  gitOpsTarget: everything
kind: VerticalPodAutoscaler
metadata:
  name: otel-collector
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: otel-collector
  updatePolicy:
    updateMode: InPlaceOrRecreate
