apiVersion: v1
kind: Secret
metadata:
    name: infisical
    namespace: kube-system
stringData:
    clientId: ENC[AES256_GCM,data:3ij3b52cr7Xh4FLveBBKxz8dBxCJhOsc8n58i+o0lAo+pFy9,iv:VobZAkBPt4lwrJTB737Fl8qjwhEPKY/SkbHiWoNzMTc=,tag:XQJmkNwFIGTFPVasi3a6fw==,type:str]
    clientSecret: ENC[AES256_GCM,data:/BioizIUppeXMbHb26pU/AItzlLiemSdFViJmV5ApDFYaZCdebyJR0fpv8tOSFH3qDk8jfTCrDPLaMsapJ7GhA==,iv:wq5/kHjL7BXASxQt7ubr4P3RQV1jXyXxrukVSqIe3vU=,tag:I6Ee3kHzEKWGaA7AkSwCIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETkNtTHcxVFpZanFKMDFE
            ZUxWanVnZU8wUHQwd2o4Zk9sQWFGWDJVTlJjCklENVNSMkc1S3U2UlBEUDhUckZ1
            Y200enBYQ3MzZWY4ajFzQ05ZVmh4c00KLS0tIE5hT0VzR3puTHR6WFlQaGtsZGJL
            YWw0cy9OdkpZdE9FeFBHdzB1ZXFmaUEKq/R79HIfybFWt1OgrRSZJ3JuvjA6oIGe
            0tk0mNup/X27qABXItBBbFfEPVY7yNoBvkyqGCG2QhTiZClB9eiLUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv78z48ynmqu29ze0z39rzqsctrergagc8zv66r6t50anaqut5vshwm6n4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTVJvQnBBYzlWaFFjeDJK
            QXdGSXJwN3IxSTJ5L2k1eUZOc01Mb0FWNVdBCmF2b25kbzhRR1JpVlhEdUlDQXdS
            R2tmUDhzeUswWDA4S01IcUVCYU9ScFkKLS0tIEVDemZHQ1ljSzFvcGNoV0JnMmRn
            UDArd0F1SkdIRnJHMVRheVZhMnZQemMKDF344VpK94XBxd6UcegXz/NSvgeQOWsV
            qtp3GVqkn8KVyPCWISe/g5eEW1k9okOwzhNMVOhDZvl3ZRzDqOmffw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1snn46rsxk30gyftene85n3deeh7un00zhg45fhqa5v73gne9jegsd5gkse
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVHNHeGZ6S0crQmd4M3Fq
            QzRJdEFSMkRLTGF4d0VnZEl2cnFyL25FdEhrCjBteUlvY1JpVkJ0RVdnR2hwNTRk
            ZndTbHNTYkdKelhtN3VscHJZMThTVEEKLS0tIG1IaFNYMHlicm1MUTltT0txWWh2
            Q1pIaVVKb2tnYUxZYW1wY0hwVW12L3MKQkQoPsuVDrcqXerLRE7z+SjpeVqdRZW6
            rZhcK6ntZ2l5H5XeaF63IUNy5vUl1mkd1jQfoU8ziA+NTRaVjuDRBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5htp8d5phq3eg34pr7l9z9q337yjd9v5v73spp4r9lkweglyu4q36js56
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T10:34:12Z"
    mac: ENC[AES256_GCM,data:SDY2Ic2rctXKtvEf8HssKVmE39FaHyB3pT4kD6m0o3SGa7sv8oHw5CpDOa0sLjW/HAp/zLm5eQ9v026duE6SdUSpe+8ONv73qE12rw/8ALlVJShIoLzRGPjM8hLSlDKvgBC4NAWwi6oOXir2YrLSZ/xsxVO1pmpzxGnF5HDRVkw=,iv:06Q+d2bnkTrTWCguosw21W3zE3O9wDA6mlFw6sHAArU=,tag:vhedBDiQy+F2ApBBoXVogg==,type:str]
    version: 3.13.2
