apiVersion: autoscaling.k8s.io/v1
ekn:
  gitOpsTarget: everything
kind: VerticalPodAutoscaler
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  targetRef:
    apiVersion: v1
    kind: Deployment
    name: notification-controller
  updatePolicy:
    updateMode: InPlaceOrRecreate
