apiVersion: autoscaling.k8s.io/v1
ekn:
  gitOpsTarget: everything
kind: VerticalPodAutoscaler
metadata:
  name: source-watcher
  namespace: flux-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: source-watcher
  updatePolicy:
    updateMode: InPlaceOrRecreate
