apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: source-controller
  namespace: flux-system
spec:
  targetRef:
    apiVersion: v1
    kind: Deployment
    name: source-controller
  updatePolicy:
    updateMode: InPlaceOrRecreate
